### PR TITLE
Update collection / set report, #935

### PR DESCRIPTION
**Pull request by njkim**
Update collection / set report, #935

Rearrange the tabs.
Move related project and textual reference to its own tab

### CODE REVIEW

**Review by aarongundel — CHANGES_REQUESTED** [review]
@njkim this looks pretty good, I think we should change the related project tab to be a table (and rename the tab/header to related **projects.**  It seems like there can be multiple related projects, although I can't recall how that relationship works in the workflows.  LMK if you think differently.

**Comment by njkim** [comment]
The related projects node are interesting one. Because the cardinality = 1 but it is still a list node (resource instance list).
So, the related projects tab appears as mixture of what is typically done for cardinality 1 and n.

**Review by aarongundel — APPROVED** [review]
looks good!

**Review by aarongundel — APPROVED** [review]
lgtm

**Pull request merged**
