### PR TITLE
adds observation type input to workflow steps #1449

### PR DESCRIPTION
**Pull request by chrabyrd**

### CODE REVIEW

**Review by chiatt — CHANGES_REQUESTED** [review]
This looks good; it adds the observation type tile as expected. However, if a user advances to the next step, and then returns to the observation step and changes the value, the change is not reflected in the tile.

**Comment by chrabyrd** [comment]
> This looks good; it adds the observation type tile as expected. However, if a user advances to the next step, and then returns to the observation step and changes the value, the change is not reflected in the tile.

@chiatt This is symptomatic of a larger issue. If a user completes the step then goes back and changes a value in the step, instead of the change being applied to the tile, a second tile is created. I will fix the observation tiles/steps as part of this ticket but we should file a follow-up ticket to check/correct all steps for this behavior.

**Comment by chiatt** [comment]
> > This looks good; it adds the observation type tile as expected. However, if a user advances to the next step, and then returns to the observation step and changes the value, the change is not reflected in the tile.
> 
> @chiatt This is symptomatic of a larger issue. If a user completes the step then goes back and changes a value in the step, instead of the change being applied to the tile, a second tile is created. I will fix the observation tiles/steps as part of this ticket but we should file a follow-up ticket to check/correct all steps for this behavior.

https://github.com/archesproject/arches-for-science/issues/1451

**Comment by chrabyrd** [comment]
> This looks good; it adds the observation type tile as expected. However, if a user advances to the next step, and then returns to the observation step and changes the value, the change is not reflected in the tile.

@chiatt resolved in latest 👍

**Review by chiatt — APPROVED** [review]

**Pull request merged**
