### PR TITLE
add depicts node to Physical Thing

### PR DESCRIPTION
**Pull request by annabelleee**
Added depicts node to Physical Thing model, but I notice there are other changes in the model that I did not make. Please check to make sure this is okay since I used the model version on https://afs.test.fargeo.com/.

### CODE REVIEW

**Comment by chiatt** [comment]
Thanks @annabelleee, I'll have a look

**Comment by chiatt** [comment]
@annabelleee I think a lot of the changes can be explained by some recent database migrations, but it looks like there might be an unintended node, `New_Node_1`. 
image

**Comment by annabelleee** [comment]
You're right. I didn't see that and I thought I deleted all the extra nodes. Should I close this and create a new PR?

**Comment by annabelleee** [comment]
@chiatt See above. I just pushed the commit where I removed that extra node.

**Pull request closed without merging**
