### PR TITLE
Analysis area annotation saving django view, #972

### PR DESCRIPTION
**Pull request by njkim**
Port the annotation steps in analysis area and sampling activity workflows.

This pr is dependent on the core arches change in
https://github.com/archesproject/arches/pull/9003

### CODE REVIEW

**Review by apeters — CHANGES_REQUESTED** [review]
It looks like the following data isn't being saved (compared to what was being saved previously).  Maybe these are default values that aren't getting picked up?

Physical Thing (Sample)
- Name_Type
- Name_Language
- Statement_language 

Physical Thing (Sample Area)
- Sample Name_Type
- Sample Name_Language

**Comment by njkim** [comment]
@apeters Thanks.
The name type, language and the statement language defaults are added to the tiles.

**Review by apeters — CHANGES_REQUESTED** [review]
After saving an annotation, the next step of the workflow is not available and the user can't move to the next step.
Screen Shot 2022-10-03 at 4 11 22 PM

**Comment by apeters** [comment]
After testing a bit more, things seem to work as desired.

**Review by apeters — APPROVED** [review]
this works as designed

**Pull request merged**
